export default `
subscription{
        shows_mutated {
            key
            event
            data{
                id
                title
                scenes{
                    scenes_id{
                        id
                        title
                        description
                        type
                        text
                        media{
                            id
                            type
                        }
                        options{
                            options_id{
                                id
                                key
                                value
                            }
                        }
                        color
                    }
                }
            }
        }
    }
`;
